### ISSUE TITLE
Fails on Python 3.9.1 and HA 2021.2

### ISSUE THREAD

**Issue by fmonday** [custom-components/feedparser#31]
After updating from Python 3.8.7 to 3.9.1 in a VENV on a Mac running Big Sur 11.2, the feedparser integration fails with the following error. HA was simultaneously updated from to 2021.1.5 to 2021.2.2. Oddly this also causes multiple other sensors to become unavailable (such as SSL expiry, local & available versions of HA, etc). Removing the integration resolves the other sensor errors. 

`AttributeError: module 'base64' has no attribute 'decodestring'`

  ```
  - platform: feedparser
    name: headlines
    feed_url: 'https://www.huffpost.com/section/front-page/feed?x=1'
    date_format: '%a, %b %d %I:%M %p'
    inclusions:
      - title
      - link
```

**Comment by fmonday** [comment]
See [here](https://github.com/techgaun/github-dorks/issues/43) which notes that `base64.decodestring` has been removed in Python 3.9.

**Comment by iantrich** [comment]
Fixed in 0.1.3
