### PR TITLE
Fix for Python 3.11 and HA 2023.6.x

### LINKED ISSUE #66: Feedparser fails to load in Python 3.11
Using homeassistant core 2023.3.0 (venv in Ubuntu 22.04.2 LTS on XCP-NG hypervisor on Intel NUC)

After upgrading venv python from 3.10 to 3.11 feedparser fails to load with the errors:

```
Unexpected exception importing platform custom_components.feedparser.sensor. 
AttributeError: module 'asyncio' has no attribute 'coroutine' 
```

A full trace is at the end of this report.

As a workaround, in sensor.py at line 46 I replaced:
```
@asyncio.coroutine
def async_setup_platform(
```

with:
```
"""@asyncio.coroutine"""
async def async_setup_platform(
```

Feedparser then started working as it did under python 3.10

```
2023-03-02 14:08:49.952 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.feedparser.sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/feedparser/sensor.py", line 46, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
2023-03-02 14:08:49.955 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/feedparser/sensor.py", line 46, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

### PR DESCRIPTION
**Pull request by metbril**
Fixes #66 #68 #70

### CODE REVIEW

**Comment by metbril** [comment]
cc @iantrich, who has committed a lot to this repo in the past.

**Comment by cociweb** [comment]
@iantrich what's your opinion? Can you create a new release with this PR, please?

**Comment by rgerbranda** [comment]
When will this be released?

**Comment by ogajduse** [comment]
Closing this one in favor of #72 that contains additional fixes on top of the change contained in this PR.
