### ISSUE TITLE
Feedparser fails to load in Python 3.11

### ISSUE THREAD

**Issue by wralb** [custom-components/feedparser#66]
Using homeassistant core 2023.3.0 (venv in Ubuntu 22.04.2 LTS on XCP-NG hypervisor on Intel NUC)

After upgrading venv python from 3.10 to 3.11 feedparser fails to load with the errors:

```
Unexpected exception importing platform custom_components.feedparser.sensor. 
AttributeError: module 'asyncio' has no attribute 'coroutine' 
```

A full trace is at the end of this report.

As a workaround, in sensor.py at line 46 I replaced:
```
@asyncio.coroutine
def async_setup_platform(
```

with:
```
"""@asyncio.coroutine"""
async def async_setup_platform(
```

Feedparser then started working as it did under python 3.10

```
2023-03-02 14:08:49.952 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.feedparser.sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/feedparser/sensor.py", line 46, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
2023-03-02 14:08:49.955 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/feedparser/sensor.py", line 46, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

**Comment by fmonday** [comment]
I got the same error after updating to Python 3.11.2 on MacOS 13.2.1, but the suggested workaround yielded an "unterminated string literal" error at line 47. Removing the final single quote returned Feedparser to working order: 
```
"""@asyncio.coroutine"""
async def async_setup_platform(
```

**Comment by wralb** [comment]
Thanks for spotting my typo and sharing your observation; I've corrected the original post.

**Comment by metbril** [comment]
Permalink to referred line:

https://github.com/custom-components/feedparser/blob/14e7a3fdb5464344bfa2e27e2675be3c0ff85e72/custom_components/feedparser/sensor.py#L46
